### ISSUE TITLE
"Activate Windows" visible in screenshots

### ISSUE THREAD

**Issue by ramcq** [flathub/com.endlessnetwork.missilemath#1]

**Comment by AsciiWolf** [comment]
Still the same issue. @wjt Any chance this could be fixed?

**Comment by wjt** [comment]
Want to prepare a PR?

**Comment by AsciiWolf** [comment]
Sorry, but no. I already have a huge amount of work tasks at the moment. I just noticed this issue, found the ticket and wanted to point out that it is still not fixed.
